### ISSUE TITLE
Type inference issue when calling method expecting long with an int

### ISSUE THREAD

**Issue by ccreeten** [javaparser/javasymbolsolver#228] opened 2017-05-12 15:46 UTC
Hey guys, I couldn't really find an existing issue for this, so I hope this is a valid new one. I have some example code for which the inference of the type of a method call expression fails:

```java
@Test
public void checkType() {
    String code = "class Test { long l = call(1); long call(final long i) { return i; }}";
    CompilationUnit cu = JavaParser.parse(code);
    MethodCallExpr methodCall = cu.getChildNodesByType(MethodCallExpr.class).get(0);
    JavaParserFacade parserFacade = JavaParserFacade.get(new ReflectionTypeSolver());
    Type returnType = parserFacade.getType(methodCall);
    assertThat(returnType.describe(), is(equalTo("long")));
}
```
This throws an exception:
```java
java.lang.UnsupportedOperationException: long java.lang.Integer
    at com.github.javaparser.symbolsolver.logic.InferenceContext.registerCorrespondance(InferenceContext.java:153)
    at com.github.javaparser.symbolsolver.logic.InferenceContext.registerCorrespondance(InferenceContext.java:151)
    at com.github.javaparser.symbolsolver.logic.InferenceContext.addPair(InferenceContext.java:60)
    ...
```
This happens when calling getType() on the method call expression. It does not happen when explicitely using a long literal, by appending an L to the 1 passed.

This is with:
```
javaparser-core: 3.2.3
java-symbol-solver-core: 0.5.3
```

**Comment by ccreeten** [comment] 2017-05-13 12:55
To my understanding, it seems to be a problem in the  ```registerCorrespondance``` method of the  ```InferenceContext``` class.

Currently, both the formal and actual types are primitives. The matching case in this instance is
```java
} else if (actualType.isPrimitive()) {
    registerCorrespondance(formalType, objectProvider.byName(actualType.asPrimitive().getBoxTypeQName()));
}
```
where it continues with the boxed version of the actual type, which then results in no matching case the next run. It seems like there should be a case for when both are primitives and the actual type can be promoted to the formal argument type?

**Comment by mlangkabel** [comment] 2017-06-15 09:25
With your example I have been able to reproduce the issue. However if I try to solve the return type with the following code snippet everything works fine.

```java
SymbolReference<MethodDeclaration> decl = parserFacade.solve(methodCall);
if (decl.isSolved())
{
	Type returnType = decl.getCorrespondingDeclaration().getReturnType();
}
```

**Comment by mlangkabel** [comment] 2017-06-15 10:19
Ok, it looks like we did not consider the case where both, the parameter type and the argument type is a primitive type while infering types for type parameters. I fixed that and added a test for this case :)

**Comment by ftomassetti** [comment] 2017-06-15 12:48
Thanks @mlangkabel for the progress in this one!

**Comment by mlangkabel** [comment] 2017-06-15 12:55
Thanks for merging! I'll close this one now :)

**Closed by mlangkabel** 2017-06-15 12:55 UTC
Labels: bug
